[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "20"

# Next.js with SSR support
# Netlify automatically detects Next.js and uses the correct runtime

[dev]
  command = "npm run dev"
  port = 3000
  targetPort = 3000
  autoLaunch = false
